version: '3.4'

services:
  postgres:
    image: postgres:12.4
    ports:
      - "5432:5432"
    volumes:
      - pg-dataset:/home/nandagopal/kootal_app_local/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  kootal-app :
    image : nandhacj/kootal-billing-app:latest
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED : 1
    depends_on:
      - postgres


volumes:
  pg-dataset:
  pg-admin-dataset: